apiVersion: apps/v1
kind: Deployment
metadata:
  name: asdn-project
  namespace: asdn
  labels:
    app: asdn-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asdn-project
  template:
    metadata:
      labels:
        app: asdn-project
    spec:
      containers:
        - name: asdn-project
          image: grafanaw/asdn_project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
